version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestProjectFlow2204Project
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.testprojectflow2204.integrations:testFlow1
  packages:
  - name: TestProjectFlow2204Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2047
